export enum EToastMessage {
  ADD_USER_SUCCESS = 'Add user successfully',
  UPDATE_USER_SUCCESS = 'Update successfully',
  SIGN_IN_SUCCES = 'Sign in successfully',
  DELETE_SUCCESS = 'Delete successfully',
  DELETE_FAILED = 'Delete failed',
  RESET_PASSWORD_SUCCESS = 'Reset password successfully',
  CHANGE_ROLE_SUCCESS = 'Change successfully',
  CHANGE_PASSWORD_SUCCESS = 'Change password successfully',
  FAIL = 'Fail',
  ADD_CATEGORY_SUCCESS = 'Add category successfully',
  UPDATE_CATEGORY_SUCCESS = 'Update category successfully',
  ADD_PRODUCT_SUCCESS = 'Add product successfully',
  UPDATE_PRODUCT_SUCCESS = 'Update product successfully',
}
